FROM  nvidia/cuda:10.2-runtime

RUN apt-get update && apt-get install -y python3.7 python3.7-dev python3.7-distutils python3-pip curl git bash nano mlocate

# Set default Python version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
RUN update-alternatives --set python3 /usr/bin/python3.7

WORKDIR /opt/service
COPY requirements.txt .

RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

COPY . .

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1

RUN ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so.10.2 /usr/lib/x86_64-linux-gnu/libcudart.so.10.1

# EXPOSE 5011

# ENTRYPOINT ["python3", "server.py"]
CMD ["/bin/bash"]
